---
abstract: 'Socket.IO protocol implementation'
author:
  - 'Viacheslav Tykhanovskyi, C<vti@cpan.org>.'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: protocol-socketio
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Protocol::SocketIO:
    file: lib/Protocol/SocketIO.pm
    version: 0.05
  Protocol::SocketIO::Handshake:
    file: lib/Protocol/SocketIO/Handshake.pm
  Protocol::SocketIO::Message:
    file: lib/Protocol/SocketIO/Message.pm
  Protocol::SocketIO::Path:
    file: lib/Protocol/SocketIO/Path.pm
requires:
  Encode: 0
  JSON: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/vti/protocol-socketio/issues
  homepage: https://github.com/vti/protocol-socketio
  repository: git://github.com/vti/protocol-socketio.git
version: 0.05
x_contributors:
  - 'vti <viacheslav.t@gmail.com>'
